package test;

import static org.testng.Assert.assertEquals;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.Test;
import pages.genericMethods;
import config.api_call;
import org.testng.annotations.Listeners;
import org.testng.ITestContext;
import com.google.common.base.Stopwatch;
import java.util.concurrent.TimeUnit;

@Listeners(listeners.listeners_sandbox.class)
public class
C4000380
extends baseTest{
	
	static WebDriver driver;
	int ordinalNum;
	String stepName;
	String stepTypeName;
	String stepID;
	String section;
	
	
	
	@Test
	public void 
test(ITestContext testContext)
throws InterruptedException, Exception {
	genericMethods z = new genericMethods(driver);
		
tcVersion ="1.00";
stepID = "4000732";
stepTypeName = "";
stepName = "SetUp_Launch Browser";
ordinalNum = ordinalNum+1;
section = "Setup";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
api_call.startSetUp(execID, stepID,stepName);
stepID = "4100205";
stepTypeName = "Launch Browser";
stepName = "Launch Browser";
ordinalNum = ordinalNum+1;
section = "Setup";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.setBrowser("chrome");
genericMethods zc = new genericMethods(driver_chrome);
api_call.startSetUp(execID, stepID,stepName);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4100411";
stepTypeName = "Set Base URL";
stepName = "Set Base URL";
ordinalNum = ordinalNum+1;
section = "Setup";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.getURL("https://zsbportal-stage.zebra.com/");
api_call.startSetUp(execID, stepID,stepName);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4100412";
stepTypeName = "Click";
stepName = "Click Sign In with your email";
ordinalNum = ordinalNum+1;
section = "Setup";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//button[contains(text(),'Sign In with your email')]");
api_call.startSetUp(execID, stepID,stepName);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4106890";
stepTypeName = "Set Text";
stepName = "Input username";
ordinalNum = ordinalNum+1;
section = "Setup";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.sendText("xpath", "//input[@id='username']", "sohoswdvt1335.idc@outlook.com");
api_call.startSetUp(execID, stepID,stepName);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4106555";
stepTypeName = "Set Text";
stepName = "input password";
ordinalNum = ordinalNum+1;
section = "Setup";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.sendText("xpath", "//input[@id='password']", "BeMore!23456");
api_call.startSetUp(execID, stepID,stepName);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4100166";
stepTypeName = "Click";
stepName = "Click Sign In";
ordinalNum = ordinalNum+1;
section = "Setup";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//button[@id='submit_id']");
api_call.startSetUp(execID, stepID,stepName);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4103565";
stepTypeName = "Minimize and Maximize the webpage ";
stepName = "Minimize and Maximize the webpage ";
ordinalNum = ordinalNum+1;
section = "Setup";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.windowMaxMin("maximize");
api_call.startSetUp(execID, stepID,stepName);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4105575";
stepTypeName = "Set Delay";
stepName = "Set Delay";
ordinalNum = ordinalNum+1;
section = "Setup";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.delay(3000);
api_call.startSetUp(execID, stepID,stepName);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
testContext.setAttribute("stop_watch_setup",watch.elapsed(TimeUnit.SECONDS));
watch = Stopwatch.createStarted();
stepID = "4000380";
stepTypeName = "";
stepName = "TDMSTest_45235";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
api_call.startMain(execID);
stepID = "4101539";
stepTypeName = "Click";
stepName = "Click Design a Label";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//span[text()='Design a Label']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4101540";
stepTypeName = "Click";
stepName = "Click Create New Design";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//span[contains(text(),'Create New Design')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4101904";
stepTypeName = "Click";
stepName = "Click Media available on your current printers";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//*[text()='XL Shipping']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4101212";
stepTypeName = "Click";
stepName = "Click Continue";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//span[contains(text(),'Continue')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4105575";
stepTypeName = "Set Delay";
stepName = "Set Delay";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.delay(3000);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107776";
stepTypeName = "Give Name to a Label";
stepName = "Give Name to a Label";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.renameLabel("Test_Case_45235");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4101657";
stepTypeName = "Click";
stepName = "Click Add text";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//button[contains(@title,'Add text')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107784";
stepTypeName = "Drop object on Canvas";
stepName = "Drop object on Canvas";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.dropOnCanvas("xpath", "//canvas[contains(@class,'upper-canvas')]", -500, -170,"@text1");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4105902";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties click source";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//ng-select[@formcontrolname='source']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4105903";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties Prompt At Print";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//span[text()='Prompt At Print']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107426";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//ng-select[@bindvalue='value']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107793";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//span[text()='Currency']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107796";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties currency drop down list";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//ng-select[contains(@data-id,'currency')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107799";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties USD/CAD";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//ng-dropdown-panel[contains(@aria-label,'Options list')]//span[text()='USD/CAD']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107823";
stepTypeName = "Set Text";
stepName = "Set Text initialValue 123";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.sendText("xpath", "//input[@data-id='initialValue']", "123");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4101657";
stepTypeName = "Click";
stepName = "Click Add text";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//button[contains(@title,'Add text')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107802";
stepTypeName = "Drop object on Canvas";
stepName = "Drop object on Canvas  text2";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.dropOnCanvas("xpath", "//canvas[contains(@class,'upper-canvas')]", -450, -170,"@text2");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107804";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties click source";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//ng-select[@formcontrolname='source']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107805";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties Prompt At Print";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//span[text()='Prompt At Print']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107807";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//ng-select[@bindvalue='value']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107808";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//span[text()='Currency']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107809";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties currency drop down list";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//ng-select[contains(@data-id,'currency')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107811";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties EUR";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//ng-dropdown-panel[contains(@aria-label,'Options list')]//span[text()='EUR']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107824";
stepTypeName = "Set Text";
stepName = "Set Text initialValue 456";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.sendText("xpath", "//input[@data-id='initialValue']", "456");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107827";
stepTypeName = "Set Text";
stepName = "Set Text Label value text2";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.sendText("xpath", "//input[@placeholder='Enter label']", "Label value text2");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4101657";
stepTypeName = "Click";
stepName = "Click Add text";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//button[contains(@title,'Add text')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107812";
stepTypeName = "Drop object on Canvas";
stepName = "Drop object on Canvas text3";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.dropOnCanvas("xpath", "//canvas[contains(@class,'upper-canvas')]", -300, -170,"@text3");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107813";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties click source";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//ng-select[@formcontrolname='source']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107814";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties Prompt At Print";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//span[text()='Prompt At Print']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107816";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//ng-select[@bindvalue='value']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107817";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//span[text()='Currency']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107819";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties currency drop down list";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//ng-select[contains(@data-id,'currency')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107820";
stepTypeName = "Click on LDA Object Properties";
stepName = "Click on LDA Object Properties GBP";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.objectClick("xpath", "//ng-dropdown-panel[contains(@aria-label,'Options list')]//span[text()='GBP']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107828";
stepTypeName = "Set Text";
stepName = "Set Text Label value Text_2";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.sendText("xpath", "//input[@placeholder='Enter label']", "Label value Text_2");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107962";
stepTypeName = "Click";
stepName = "Click Print button in LDA";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//button[contains(@data-id,'printLabel')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4100455";
stepTypeName = "Switch to main frame";
stepName = "Switch to main frame";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.switchToMainFrame();
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4105575";
stepTypeName = "Set Delay";
stepName = "Set Delay";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.delay(3000);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4108022";
stepTypeName = "Key board actions";
stepName = "Key board actions";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.keyboardActions("xpath", "//input[@data-testid = 'input-text-input-field']", "right","!@#",0);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0, section);
stepID = "4107969";
stepTypeName = "Get attribute and compare with expected";
stepName = "Get attribute and compare with expected value=123.00";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.getAttributeAndCompare("xpath", "//input[@data-testid = 'input-text-input-field']", "value","123.00");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107965";
stepTypeName = "Set Text";
stepName = "Set Text 1000";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.sendText("xpath", "//input[@data-testid = 'input-text-input-field']", "1000");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107967";
stepTypeName = "Set Delay";
stepName = "Set Delay";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.delay(1000);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107966";
stepTypeName = "Click";
stepName = "Click Print button in preview";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//span[contains(text(),'Print')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107622";
stepTypeName = "Click";
stepName = "Click close the print preview page";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//button[@data-testid='close-button']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4100449";
stepTypeName = "Switch to Frame";
stepName = "Switch to Frame";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.switchToFrame("xpath", "//iframe[contains(@title,'Designer')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4103983";
stepTypeName = "Click";
stepName = "Click Exit designer";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//span[contains(text(),'Exit designer')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4100455";
stepTypeName = "Switch to main frame";
stepName = "Switch to main frame";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.switchToMainFrame();
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107520";
stepTypeName = "Key board actions";
stepName = "Key board actions ";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.keyboardActions("xpath", "//input[@data-testid='input-text-input-field']", "enter","Test_Case_45235",1);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0, section);
stepID = "4107524";
stepTypeName = "Click";
stepName = "Click Test_Case_45235";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//div[contains(text(), 'Test_Case_45235')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4101144";
stepTypeName = "Click";
stepName = "Click Print option";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//span[contains(text(),'Print')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4105575";
stepTypeName = "Set Delay";
stepName = "Set Delay";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.delay(3000);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4101388";
stepTypeName = "Click";
stepName = "Click Print button in preview";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//span[contains(text(),'Print')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4105575";
stepTypeName = "Set Delay";
stepName = "Set Delay";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.delay(3000);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4108019";
stepTypeName = "Key board actions";
stepName = "Key board actions";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.keyboardActions("xpath", "//input[@data-testid = 'input-text-input-field']", "right","abc",0);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0, section);
stepID = "4107977";
stepTypeName = "Get attribute and compare with expected";
stepName = "Get attribute and compare with expected value=123.00";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.getAttributeAndCompare("xpath", "//input[@data-testid = 'input-text-input-field']", "value","123.00");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107978";
stepTypeName = "Set Text";
stepName = "Set Text -2000.12";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.sendText("xpath", "//input[@data-testid = 'input-text-input-field']", "-2000.12");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4105575";
stepTypeName = "Set Delay";
stepName = "Set Delay";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.delay(3000);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4101388";
stepTypeName = "Click";
stepName = "Click Print button in preview";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//span[contains(text(),'Print')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107980";
stepTypeName = "Check element status";
stepName = "Check element status Print job sent";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.checkElement("xpath", "//div[@data-testid='toast']", "isPresent");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107622";
stepTypeName = "Click";
stepName = "Click close the print preview page";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//button[@data-testid='close-button']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4108020";
stepTypeName = "Click";
stepName = "Click Test_Case_45235";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//div[contains(text(), 'Test_Case_45235')]");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4104263";
stepTypeName = "Click";
stepName = "Click Delete";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//span[text()='Delete']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4108021";
stepTypeName = "Set Delay";
stepName = "Set Delay";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.delay(1000);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4107629";
stepTypeName = "Click";
stepName = "Click Delete confirm";
ordinalNum = ordinalNum+1;
section = "Main";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//span[text()='Delete']");
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
testContext.setAttribute("stop_watch_main",watch.elapsed(TimeUnit.SECONDS));
watch = Stopwatch.createStarted();
stepID = "4000740";
stepTypeName = "";
stepName = "CleanUp_Close Browser";
ordinalNum = ordinalNum+1;
section = "Cleanup";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
api_call.startCleanUp(execID, stepID,stepName);
stepID = "4106902";
stepTypeName = "Click";
stepName = "Click user-menu-avatar";
ordinalNum = ordinalNum+1;
section = "Cleanup";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//div[contains(@data-testid,'user-menu-avatar')]");
api_call.startCleanUp(execID, stepID,stepName);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4106604";
stepTypeName = "Click";
stepName = "Click";
ordinalNum = ordinalNum+1;
section = "Cleanup";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
z.Click("xpath", "//span[contains(text(),'Log Out')]");
api_call.startCleanUp(execID, stepID,stepName);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
stepID = "4100347";
stepTypeName = "Close Browser";
stepName = "Close Browser";
ordinalNum = ordinalNum+1;
section = "Cleanup";
testContext.setAttribute("stepID", stepID);
testContext.setAttribute("stepTypeName", stepTypeName);
testContext.setAttribute("stepName", stepName);
testContext.setAttribute("ordinalNum", ordinalNum);
testContext.setAttribute("section", section);
zc.closeBrowser();
api_call.startCleanUp(execID, stepID,stepName);
api_call.insertStep(execID, ordinalNum, stepID, stepTypeName, stepName, "Pass", 0,section);
testContext.setAttribute("stop_watch_cleanup",watch.elapsed(TimeUnit.SECONDS));
	}
	

}
